kumuluzee:
  name: rso-restaurant
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
  logs:
    config-file:  '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="restaurant">
                          <Appenders>
                              <Console name="console" target="SYSTEM_OUT">
                                  <PatternLayout pattern="%d %p %marker %m %X %ex %n"/>
                              </Console>
                              <Socket name="logstash" host="c322641a-8fb8-4799-9040-d4be6a8cc675-ls.logit.io" port="13437" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="all">
                                  <AppenderRef ref="logstash" level="trace"/>
                              </Root>
                              <AsyncLogger name="si.fri.rso.projekt.order.api.v1.resources.RestaurantApi" level="trace" additivity="false" includeLocation="true">
                                <AppenderRef ref="logstash"/>
                              </AsyncLogger>
                          </Loggers>
                      </Configuration>'
app-properties:
  external-services:
    enabled: false