kumuluzee:
  name: rso-restaurant
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8085
    http:
      port: 8085
  config:
    etcd:
      hosts: http://etcd:2379
  discovery:
    etcd:
      hosts: http://etcd:2379
  metrics:
    web-instrumentation:
    - name: restaurants-service
      url-pattern: /v1/restaurants/service
    - name: restaurants-endpoint
      url-pattern: /v1/restaurants/
  logs:
    config-file:  '<?xml version="1.0" encoding="UTF-8"?>
                      <Configuration name="restaurant">
                          <Appenders>
                              <Socket name="logstash" host="c322641a-8fb8-4799-9040-d4be6a8cc675-ls.logit.io" port="13437" protocol="tcp">
                                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
                              </Socket>
                          </Appenders>
                          <Loggers>
                              <!-- Default logger -->
                              <Root level="INFO">
                                  <AppenderRef ref="logstash" level="info"/>
                              </Root>
                          </Loggers>
                      </Configuration>'
app-properties:
  external-services:
    enabled: false